### ISSUE TITLE
Failed to parse message: InvalidMarkerRead(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })                                                                                                        

### ISSUE THREAD

**Issue by JasonSanDiego** [ivabus/lonelyradio#4]
When playing a song, I get this error message. Other songs work, so maybe there is some issue with this mp3 being malformed or maybe it was a transient issue while connecting. Regardless, it seems like the server should catch this error gracefully, show an error message, and move on to the next song. In this case, it acts like it's playing the song with the timer running, but nothing is playing.

```
Playing: Avril Lavigne - 2002 Billboard Top 100 Hits - Sk8er Boi (3:24)thread '<unnamed>' panicked at monolib/src/lib.rs:281:47:
Failed to parse message: InvalidMarkerRead(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Playing: Avril Lavigne - 2002 Billboard Top 100 Hits - Sk8er Boi (4:21 / 3:24) [1.00]     
```

**Comment by ivabus** [comment]
Can you please attach the log from the server? It's most likely the problem with decoding

**Comment by JasonSanDiego** [comment]
Yep, I'm seeing a fair number of these errors:
```
thread 'tokio-runtime-worker' panicked at src/encode.rs:49:18:
called `Result::unwrap()` on an `Err` value: Config(VerifyError { components: ["input.framebuf"], reason: "input sample must be in the range of bits=24" })
```

**Comment by JasonSanDiego** [comment]
It's also worth noting that this happens sometimes in the middle of the track playing successfully, so it doesn't necessarily seem to be an issue of the entire track itself being encoded with the wrong sample rate.

**Comment by ivabus** [comment]
I think I fixed it some time ago, could you please reinstall the server from a master branch and try again?

**Comment by JasonSanDiego** [comment]
I reinstalled and things are a lot better but it's still far from reliable. Previously, it would crash before even playing a full song. Now, I get through 1-3 songs before it crashes. Same error as mentioned above.
